apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-management-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
